### ISSUE TITLE
Recommended way for integrating with Webpack API?

### ISSUE THREAD

**Issue by Aghassi** [shellscape/webpack-plugin-serve#115]
Hello 👋 ,

I've been playing around with this plugin, and I'm having quite a bit of trouble transitioning from Webpack Dev Server to this to test with. Currently, here is my situation:

1. I'm running Webpack Dev Server via its API and creating a config and `compiler` for Webpack depending on the context.
2. I'm using `html-webpack-plugin` with a template to generate the entry file for webpack.
3. I'm setting all the `devServer` bits as usual.

The closest I have gotten to getting parity with this plugin is to:
1. Strip the `devServer` bit out of my config and set similar options (though `http2` seems to cause the server to not bootstrap correctly, so I have it set to false currently)
2. This doesn't seem to pick up the `index.html` that `html-webpack-plugin` generates, hence I'm not sure how or where to point it because that is never written to disk as far as I can tell.
3. If I point this to my template html, that is no good because I can't find the bundles generated by webpack (since they are in memory to my knowledge, not on dis), so the `static` setting can't find them.

Are there any better docs with integrating with Webpack via the API, instead of just listing the configs?

**Comment by smashercosmo** [comment]
Can't say anything about http2, but webpack-plugin-serve writes all the files to the disc, including index.html, generated by html-webpack-plugin. It doesn't use webpacks memory file system. Check the ```examples``` folder. There you can find different webpack-plugin-serve usage examples. For instance https://github.com/shellscape/webpack-plugin-serve/tree/master/recipes/react.

**Comment by PlayMa256** [comment]
Can you share your configs? So we can check http2 and what you are trying to do

**Comment by shellscape** [comment]
Thanks for opening this issue. Feedback like this is essential.

> Are there any better docs with integrating with Webpack via the API, instead of just listing the configs?

This is interesting. There is no separate API for the plugin, because it's just a plugin. webpack-dev-server creates too much "magic," and it leads to confusion like this. If you'd like to use this plugin via webpack without an API, you would use the webpack API directly. [`webpack-nano`](https://github.com/shellscape/webpack-nano) does exactly that, but to act as a CLI. Now, webpack-nano does a lot more than you'll need, but it should serve as a good working example of how to use the webpack api. For what it's worth, that's all that webpack-dev-server's API is doing.

Here's a very simple API example for webpack, from webpack-nano:

```js
const webpack = require('webpack');
const config = require('<path>/webpack.config.js');

const compiler = webpack(config);
const done = (fatal, stats) => {
  if (fatal) {
    log.error(fatal);
    return;
  }

  const statsOptions = { ... };
  const result = stats.toString(statsOptions);
  const { log } = console;
  log(result);
};

const watch = true; // most users in this scenario will want to watch files for HMR
if (watch) {
  const watchOptions = { ... };
  compiler.watch(watchOptions, done);
} else {
  compiler.run(done);
}
```

I think a migration document is a wise idea.

> 1. Strip the devServer bit out of my config and set similar options (though http2 seems to cause the server to not bootstrap correctly, so I have it set to false currently)

That's the right path to take. Regarding `http2`, it can be finicky within Node itself, but we haven't had a lot of users on http2 with the plugin as yet, so it's exciting that you are. I'd be happy to take a look at your repo to see if there's something we need to change to accomodate your setup better. We'd like to make sure you're not getting issues with using http2.

> 2. This doesn't seem to pick up the index.html that html-webpack-plugin generates, hence I'm not sure how or where to point it because that is never written to disk as far as I can tell.

As @smashercosmo mentioned, the plugin doesn't use a memory file system (WDS does), so your files are written to the specified output directory. _(Webpack defaults that to a `/dist` directory)_. This plugin doesn't affect other plugins, so as long as other plugins are configured correctly, webpack should run them as normal. Look for your output HTML file from html-webpack-plugin, and add the output location to the [`static`](https://github.com/shellscape/webpack-plugin-serve#static) setting.

> 3. If I point this to my template html, that is no good because I can't find the bundles generated by webpack (since they are in memory to my knowledge, not on dis), so the static setting can't find them.

The key here is to look for the files where your `output` config property (for webpack itself) is set to write to. (If that's not set, look for the `dist` directory mentioned above). Again this is good feedback, because webpack-dev-server keeps everything in memory, and we should mention this in a migration doc.

**Comment by Aghassi** [comment]
Unfortunately I can't share the repo, it is internal to my company. I will try again, some things off the top of my head that were confusing when I tried last night:

1. `html-webpack-plugin` was not outputting a file for me to my output path... so I will have to dig into that.
2. When I ran the API the way @shellscape suggested, I remember webpack building and not starting a server to listen on.

I will double check again and see if I can make any headway on this. I'll post back here as I find things.

**Comment by shellscape** [comment]
If I/we can help you construct a repo with a similar structure as your app, I would be happy to. We could all collaborate on it to get you where you need to be, and it would serve as a great example for folks.

**Comment by Aghassi** [comment]
Yeah let me see what I can throw together

**Comment by PlayMa256** [comment]
If we can help on something, just let us know!

**Comment by shellscape** [comment]
@Aghassi checking in on this. don't want to let it go too stale. as well, if this has already been resolved we'd like to close 😄

**Comment by Aghassi** [comment]
Works been crazy, haven’t had a chance to setup a demo repo. Let me see if I can get it done sooner rather than later. No guarantees. I think the main thing for me, assuming this repo does it, is that Webpack dev server his not performant. It pegs your CPU at like 100% when you are doing nothing. I _think_ this repo may solve that, but I have yet to vet and check.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shellscape** [comment]
OK no worries at all. In the mean time, I'm going to close this issues as "on hold". When you have time to investigate, please drop a quick ping on the issue and I'll reopen.
