### ISSUE TITLE
ECONNRESET with historyfallback when using window.postMessage

### ISSUE THREAD

**Issue by jeremy-coleman** [shellscape/webpack-plugin-serve#127]
```text
getting the following when closing a web app (react) tab component with 
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  headerSent: true }

doesn't happen with webpack dev server
doesn't happen with parcel serve
doesnt happen with browser sync and connect api history fallback/ webpack middle ware stuff

doesn't crash the process, so not really a big deal i think. 
```

![image](https://user-images.githubusercontent.com/25135855/56711129-748f1480-66f7-11e9-8331-37408ae17087.png)

**Comment by jeremy-coleman** [comment]
basically, i open that small component in a host window (kind of like a vscode tab window) , and when i close it - i get an error in the node console. it doesn't happen with other components , only ones using postMessage.

**Comment by shellscape** [comment]
hey there. It's generally frowned upon on Github to ignore pre-made issue templates, or to remove their content, especially when reporting issues that may be bugs. It's also good practice to utilize the _Edit_ function of a post or reply, rather than post successive messages.

we're happy to help with this, but please respect the time and effort of maintainers by going back and updating your original post with the appropriate template.

**Comment by jeremy-coleman** [comment]
cool, thanks for the response, closing because my question/concern seems to already be known and as i suspected not a big deal. Sorry about the template, but there was no way to give you a reproducible version without a mile of mostly unnecessary code
