### ISSUE TITLE
Issue when using disableDotRule of historyFallback

### ISSUE THREAD

**Issue by sibelius** [shellscape/webpack-plugin-serve#130]
- Webpack Version: 4.25.1
- Operating System (or Browser): MacOS
- Node Version: 10.15.0
- webpack-plugin-serve Version: 0.5.0 and 0.8.0

### How Do We Reproduce?

You can run `yarn start:web` on this pull requests https://github.com/entria/entria-fullstack/pull/76

### Expected Behavior
- [ ] it should render web app
- [ ] it should accept `.` on http url

### Actual Behavior
- [ ] it does not render anything
it gives us `Uncaught SyntaxError: Unexpected token <`

here is the logs from historyApiFallback

```jsx
Rewriting GET / to /index.html
Rewriting GET /bundle.js to /index.html
Rewriting GET / to /index.html
Rewriting GET /bundle.js to /index.html
```

I think the problem is that `bundle.js` is not treated differently

**Comment by sibelius** [comment]
workaround for now:

```jsx
historyFallback: {
        disableDotRule: true,
        verbose: true,
        rewrites: [
          {
            from: '/wps',
            to: (context) => (context.parsedUrl.pathname),
          },
          {
            from: '/bundle.js',
            to: (context) => (context.parsedUrl.pathname),
          },
          {
            from: '/sw.js',
            to: (context) => (context.parsedUrl.pathname),
          },
        ],
      },
      static: [outputPath],
      status: false,
    }),
```

I think it should not send accept headers for `.js` files

this config works well on webpack-dev-server

**Comment by PlayMa256** [comment]
Apparently it is falling in the same problem we were having with /wps, where it has accept headers and `connect-history-api-fallback` is ignoring it.

**Comment by PlayMa256** [comment]
similar to #94 , when removing accept headers it works as intended. Now why `connect-history-api-fallback` is breaking at this... is going to be difficult to know!

**Comment by shellscape** [comment]
OK so we have to make some more considerations for headers @PlayMa256 ?

**Comment by PlayMa256** [comment]
Seems that we need @shellscape.
I went on a debug session with @sibelius and also searching on github issues, i found that people were also complaining about a similar problem where other assets with accept header were being redirected to /index as well. During the debug, we removed `*/*` from headers and everything worked as expected, we were having /bundle not being redirected to /index.html.

And as we can see, the creator of `connect-history-api-fallback` doesn't want to deal with it, because "there has been too many downloads without this problem".

I would bet on removing `*/*` from accept header, or even remove the whole property.

**Comment by shellscape** [comment]
Adding the following to the serve options might work then:

```js
middleware(app) {
  app.use(async (ctx, next) => {
    const { accept, ...headers } = ctx.request.header;
    ctx.request.header = headers;

    await next();
  });
}
```

**Comment by PlayMa256** [comment]
Yeah, it will!
I'll submit a pr to handle it. I wanted to bring the discussion in order to find a suitable solution actually :)

**Comment by PlayMa256** [comment]
It will!
Should we also handle that on our side by default?

**Comment by shellscape** [comment]
I'm not so sure that's the right fix, because that removes the accept header from _every_ request. We should think on how to solve this without interfering with others who might be looking for that header.

**Comment by sibelius** [comment]
can we just remove the headers for non `.html` files?

or should we have this as a new param?

**Comment by shellscape** [comment]
What if we supported a `!` for the headers option that would remove a header from the response? Similar to how globs work.

**Comment by PlayMa256** [comment]
I guess that would make more sense if we could filter the headers for non-html files, because if we add ! for headers removing them, that would create a big hussle for scenarios like this that sibelius showed.

**Comment by shellscape** [comment]
> because if we add ! for headers removing them, that would create a big hussle for scenarios like this that sibelius showed.

haha not quite sure that came across right in translation. did you mean `hassle`? (if so, please explain)

**Comment by PlayMa256** [comment]
I guess that would work fine but, wouldn't that insert a new layer if complexity for the user? This would need to be 100% documented, the problem and what the user would have to do.

**Comment by sibelius** [comment]
using this

```jsx
middleware(app) {
  app.use(async (ctx, next) => {
    const { accept, ...headers } = ctx.request.header;
    ctx.request.header = headers;

    await next();
  });
}
```

does not work well

it won't rewrite anything

`Not rewriting GET /sw.js because the client did not send an HTTP accept header.`
`Not rewriting GET /home because the client did not send an HTTP accept header.`

**Comment by shellscape** [comment]
@sibelius what about filtering out the `*/*` header from paths that terminate with `.html` in the same kind of handler? e.g. something like:

```js
middleware(app) {
  app.use(async (ctx, next) => {
    if (/\.html$/.test(ctx.path)) {
      let { accept } = ctx.request.header;
      accept = accept.replace(/\*\/\*/, '');
      ctx.request.header.accept= accept;
    }
    await next();
  });
}
```

**Comment by sibelius** [comment]
I current config to fix historyFallback is like this:

```jsx
historyFallback: {
        disableDotRule: true,
        verbose: true,
        rewrites: [
          {
            from: '/wps',
            to: context => context.parsedUrl.pathname,
          },
          {
            from: /.js/,
            to: context => context.parsedUrl.pathname,
          },
        ],
      },
```

**Comment by shellscape** [comment]
@sibelius but can you test the possible solution above?

**Comment by sibelius** [comment]
using the middleware above I've got

Uncaught SyntaxError: Unexpected token <

in all pages

this is the bug:
> Rewriting GET /bundle.js to /index.html

it should not rewrite .js files

**Comment by shellscape** [comment]
So much time passes between each comment that I lose track of the context.

What's your proposed solution to fix this?

**Comment by sibelius** [comment]
Let’s keep it there

**Comment by shellscape** [comment]
OK cool. I'll add this to the FAQ in the mean time.

**Comment by soulofmischief** [comment]
@shellscape is there any negative consequence to using

```js
historyFallback: {
    disableDotRule: true,
    verbose: true,
    rewrites: [
      {
        from: '/wps',
        to: context => context.parsedUrl.pathname,
      },
      {
        from: /\.(?!html)/,
        to: context => context.parsedUrl.pathname,
      },
    ],
  },
```

instead?

It works at first glance and catches other filetype errors, however I won't be testing it much further because I was giving `webpack-plugin-serve` a spin since `webpack-dev-server` is having an issue with proxying over LAN, I cannot get hot module replacement to work with this plugin, or live reloading, and reloading the page takes upwards of 10 seconds.

**Comment by shellscape** [comment]
I wouldn't know of any negative consequences. You might want to ask with the `connect-history-api-fallback` folks. But it sounds your app there has bigger issues if all of that is true.

**Comment by soulofmischief** [comment]
I don't have these problems `webpack-dev-server`. My code is properly modularized and components are chunked and loaded dynamically with the correct webpack markup.

The only issue I was having with `webpack-dev-server` was with the proxying timing out over LAN, but the port and address for the proxied server work fine over LAN, it's the proxying itself which is having an error. I'm still looking into the cause, but my code is fine and well-tested. Seeing as how I thoroughly read the README for this project and implemented all of the correct settings, I'm hesitant to believe the problem is on my end. Perhaps my configuration reveals some shortcomings in this module. I wouldn't be so dismissive.
