### ISSUE TITLE
v0.9.0 breaks my project (constant "Not Found / 404" results)

### ISSUE THREAD

**Issue by G-Rath** [shellscape/webpack-plugin-serve#133]
- Webpack Version: 4.30.0
- Operating System (or Browser): Windows 10
- Node Version: v10.15.3
- webpack-plugin-serve Version: 0.9.0

### How Do We Reproduce?

My current configuration setup works fine up until version `0.9.0`; if I use this version I'm just told "Not Found / 404", and I can't figure out what changes to make to make my application work with the new version.

Here's a [repo](https://github.com/G-Rath/js-bugs/tree/webpack-plugin-serve/issue-133).

### Expected Behavior

Things work as they did in v0.8.0.

### Actual Behavior

Things do not work as they did in v0.8.0

**Comment by shellscape** [comment]
That's damn peculiar. All of our tests passed and I've been demo'ing 0.9.0 this week in live coding sessions. I'll have a look.

**Comment by G-Rath** [comment]
It could be that I'm just being really stupid with my config, but ya I spent an hour or so trying to figure out wtf was going before realising the version difference :joy:

**Comment by shellscape** [comment]
OK so it's because you're passing an array to `static`. As of v0.9.0 if an array is passed, it's run through `globby`. Unfortunately, that implementation isn't correct and your bug case revealed that. (We really need more tests around options)

What happened was that your `../js-bugs/out` static path was getting transformed into `.../forks/js-bugs/out/index.html` etc, which won't work with koa-static. So in your case just removing the array and passing a single string will fix it, but anything using arrays will probably break. I'll try and work on a fix tonight.

**Comment by G-Rath** [comment]
Don't forget to update `@types/webpack-plugin-serve` ;)

**Comment by shellscape** [comment]
@PlayMa256 ^ see previous comment. Thanks for the reminder @G-Rath

**Comment by PlayMa256** [comment]
@G-Rath its already to be merged on DT. Just waiting for it

**Comment by PlayMa256** [comment]
Merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35221
