### ISSUE TITLE
Proxy not working?

### ISSUE THREAD

**Issue by tonghae** [shellscape/webpack-plugin-serve#148]
> new WebpackPluginServe({
    historyFallback: true,
    port: 2000,
    middleware: (app, builtins) => {
        app.use('/api', builtins.proxy({ target: `http://localhost:3000` }));
    }
})

I get 
> error TS2554: Expected 1 arguments, but got 2

error when trying to use it like in example from the main page

**Comment by PlayMa256** [comment]
Where does this error is shown up? Exactly where?

**Comment by tonghae** [comment]
In webpack config if I try to add middleware to the plugin's options: https://imgur.com/a/HNXOhCo

**Comment by shellscape** [comment]
@tonghae thank you for opening an issue 🍺 

In the future please use the "Bug" issue template and fill in all of the details. That helps us to better help you, and we ask everyone to do that, even maintainers!

**Comment by shellscape** [comment]
Please see the [proxies recipe](https://github.com/shellscape/webpack-plugin-serve/blob/master/recipes/proxies.md) for functional examples of how to work with proxying. The [`middleware`](https://github.com/shellscape/webpack-plugin-serve#middleware) option's documentation state that the options should be identical to what is used with [`http-proxy-middleware`](https://github.com/chimurai/http-proxy-middleware), which expects two parameters. You've left out the `path` parameter, which is why that error was thrown.

**Comment by tonghae** [comment]
Sorry but I still don't get it. It says that there are 2 params already, but I provided only 1 argument, object with a single prop, target.
