### ISSUE TITLE
Can't find index.html

### ISSUE THREAD

**Issue by pbn04001** [shellscape/webpack-plugin-serve#175]
My index.html file is not being copied over into the dist folder, but the main.js is.  What am I missing?

```
import webpack from 'webpack'
const { WebpackPluginServe: Serve } = require('webpack-plugin-serve');
import { rules } from './webpack.base'
import path from "path"

const outputPath = path.join(process.cwd(), '/dist');

const options = {
  open: true,
  static: outputPath,
  historyFallback: true,
  liveReload: true,
  port: 8081,
  middleware: (app, builtins) => {
    app.use(builtins.proxy('/acton', { target: 'http://localhost/acton' }));
  },
};

const config: webpack.Configuration = {
  mode: 'development',
  entry: [
    './src/index.tsx',
    'webpack-plugin-serve/client',
    './src/index.html'
  ],
  resolve: {
    // Add '.ts' and '.tsx' as resolvable extensions.
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.json']
  },
  output: {
    path: outputPath,
  },
  // Enable sourcemaps for debugging webpack's output.
  devtool: "source-map",
  module: {
    rules: [
      // All files with a '.ts' or '.tsx' extension will be handled by 'awesome-typescript-loader'.
      {
        test: /\.(ts|tsx)$/,
        loader: 'awesome-typescript-loader',
        exclude: /node_modules/,
      },{
        enforce: "pre",
        test: /\.js$/,
        loader: "source-map-loader",
        exclude: /node_modules/,
      },
      ...rules
    ]
  },
  plugins: [new Serve(options)],
  watch: true,
}

export default config
```

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed portions of the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request template sections. They're in the template because they're useful to the maintainers of this project.

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
