### ISSUE TITLE
Include TypeScript types?

### ISSUE THREAD

**Issue by bebraw** [shellscape/webpack-plugin-serve#189]
### Feature Use Case

Now TypeScript types are available through `@types/webpack-plugin-serve`. The gotcha is that they get out of sync and based on my recent usage they seem quite broken even.

I looked into fixing the types over there but during this work I came up with a better idea.

I know the types were separated due to the dependency on webpack but it looks like we can change that.

### Feature Proposal

While studying the current types, I noticed that the only dependency on webpack has to do with `Compiler`. It seems it's possible to remove the direct dependency by using `class WebpackPluginServe<Compiler>` kind of generic where the user can pass the `Compiler`. It's a little extra work for the user but at the same time it breaks the explicit dependency on the heavy webpack type. The good side is that after the side the users won't need to install a separate package for the types.

If we moved the type back here, first of all it would let us keep the types in sync with the library. Perhaps longer term it could allow us to port the code to TypeScript entirely although I wouldn't do that as a first step.

**Comment by shellscape** [comment]
I'm really not open to exporting TypeScript types from the project directly. It's just yet another edge to maintain. I like that the types are in DefinitelyTyped, because they can be maintained separate from this repo by impassioned TS users. WPS doesn't use TS. So it's an add-on for folks that do. uUntil/if the project is converted to TS, it shouldn't have types (I know that this is not the case for every project, but it's how I feel about _this_ project). Every project that attempts to export TS types runs into a maintenance burden. If we saw 100k+ weekly, then I'd consider converting this to TypeScript and we'd get the type export for free.
