### ISSUE TITLE
Support Node v8

### ISSUE THREAD

**Issue by sibelius** [shellscape/webpack-plugin-serve#34]
### Expected Behavior / Situation

n/a 

### Actual Behavior / Situation

`webpack-plugin-serve` doesn't support Node v8 at the moment. Node v10 is Active LTS now, but there are a lot of people that can't move to v10 yet.

### Modification Proposal

Can we support Node v8?

**Comment by PlayMa256** [comment]
I do agree, although it is the supported LTS still too early.

Version 10 was chosen due to a problem on how node http was handling upgrade requests, which led us to choose a version that was suitable for the job and also due to performance improvements both on webpack and on http.

Although there is a workaround that can be done to be able to be used on node v8. Although we technically don't support, we won't stop others from using it.

I'll open a pr updating readme and how to use.

**Comment by shellscape** [comment]
Anyone is free to continue discussing this topic, share tips and tricks, even though the issue is closed.
