### ISSUE TITLE
Adding custom headers

### ISSUE THREAD

**Issue by kurtextrem** [shellscape/webpack-plugin-serve#36]
webpack-dev-server and webpack-serve supported adding custom headers. Have I overlooked something or is this not supported here?

Thank you in advance.

**Comment by shellscape** [comment]
@kurtextrem great question, thanks for opening an issue about it. webpack-dev-server's `headers` option is some abstract sugar on top of express. While it's used, we determined it wasn't _widely_ used. Since we run `Koa` under the hood in this plugin, it's very easy to wire up and has no restrictions on how you specify headers. Here's one way to accomplish this:

```js
// webpack.config.js
module.exports = {
  plugins: [
    new WebpackPluginServe({
      middleware: (app, builtins) =>
        app.use(async (ctx, next) => {
          await next();
          ctx.set('X-Superhero', 'batman');
        })
    })
  ]
};
```

We'll add this as a recipe in as soon as we're able to. I'll also create a voting issue for direct support of an option for this, and if it reaches enough votes, we'll add a formal option for `headers`.

**Comment by PlayMa256** [comment]
Or you can use the proxy middleware and add any header when it gets the result from your api/mocked api.

```
module.exports = {
  ...,
  plugins: [
    new WebpackPluginServe({
      middleware: (app, builtins) => {
        app.use(builtins.proxy('/api', { 
          target: 'http://10.10.10.1:1337',
          onProxyRes: (proxyRes, req, res) => {
            proxyRes.headers['x-added'] = 'foobar' // add new header to response
          }
        }));
      }
    })
  ]
};
```

**Comment by shellscape** [comment]
I have created a voting issue for the feature in #37

**Comment by kurtextrem** [comment]
Thank you Andrew and @PlayMa256 for the quick answers. Really helpful!

**Comment by shellscape** [comment]
Gonna close this one as resolved for now, but will reopen if anyone requests it.

**Comment by shellscape** [comment]
Added a recipe for this to our documentation in 2636d30
