### ISSUE TITLE
Serve output.path from output.publicPath

### ISSUE THREAD

**Issue by davidroeca** [shellscape/webpack-plugin-serve#41]
### Expected Behavior / Situation

If I set `output.publicPath` to something other than `/`, it would be very convenient if the `output.path` files could be served from this path.

```js
// does not work appropriately
const path = require('path');
// ...
const outputPath = path.join(__dirname, 'build');
module.exports = {
  // ...
  output: {
    path: outputPath,
    publicPath: '/app/',
  },
  static: outputPath,
  // I've tried with the historyFallback
  historyFallback: {
    index: '/app/index.html'
  },
}
```

### Actual Behavior / Situation

Right now, if I set `output.publicPath`, my build directory must match this, and I must also set the `static` option as well.

```js
// works
const { path } = require('path');
// ...
const publicPathName = 'app'
const outputPath = path.join(__dirname, publicPathName);
module.exports = {
  // ...
  output: {
    path: outputPath,
    publicPath: `/${publicPathName}/`,
  },
  static: outputPath,
}
```

### Modification Proposal

I understand that this works because by default this plugin will serve files from the current working directory. However, it would be much more convenient to resolve the public path as well, since `publicPath` is appended to the urls in `html-webpack-plugin`, and this seems to happen in other webpack references as well.

This works brilliantly with `webpack-serve` [here](https://github.com/davidroeca/web-app-orchestration-talk/blob/d576633e11e587970170d97c0ad0f1da93ecf0ee/working-example/app1/serve.config.js), and I'd love for it to work with this plugin as well.

Let me know if you're open to supporting this; if that's not the case, would `webpack-dev-middleware` be a feasible thing for me to mix into this plugin manually?

**Comment by shellscape** [comment]
Please see our FAQ, which outlines some information relevant to this: [Why does the static option default to compiler.context?](https://github.com/shellscape/webpack-plugin-serve/blob/master/.github/FAQ.md#why-does-the-static-option-default-to-compilercontext). In this instance you need to setup the `static` option correctly for your environment. Note that it can be an array of paths. It's flexible enough to accomodate any setup.

For every opinionated a module like this makes, it runs contrary to what others expect, and so there is no winning. It's therefore safer, less of a burden on maintainers, and better for the wider user experience, to maintain a known quantity; in this case the user must setup the config correctly for their own environment. Unfortunately that's not something open to change at the moment.

If you feel this isn't covered well enough, and you'd like to add to our [recipes](https://github.com/shellscape/webpack-plugin-serve/tree/master/recipes), that would be awesome. 🍺

**Comment by davidroeca** [comment]
Thanks for the quick reply. 

As for my question above:

> ... would webpack-dev-middleware be a feasible thing for me to mix into this plugin manually?

Looks like `webpack-dev-middleware` currently isn't a dependency of this project--was that mostly for simplicity/minimalism? 

I'd be happy to write a recipe for working with non-standard `publicPath`s when I have time to check it out, as long as this isn't counter to the design of this plugin.

**Comment by shellscape** [comment]
Sorry, I missed that bit. `webpack-dev-middleware` was intently avoided. Keeping this plugin simple was part of the reason. WDM is very flawed in a number of ways (I was the maintainer of the module for about 18 months):

- It wires up an in-memory filesystem which does more harm than good, actually slows down the time from build-to-client and it's primarily to obscure the fact that webpack is dumping a metric ton of files during watch/HMR cycles. (We've circumvented that problem )
- It makes a number of assumptions about what the user wants, and ends up requiring burdensome configuration to work correctly.
- It's far too complex for middleware, has it's own config set and nuances

Aside from those reasons, it's a good quick addition to an existing express-like server. But it's not ideal for an all-encompassing development server experience. All that said, it _would not_ be feasible to mix in WDM into this plugin, because this plugin already performs all of the actions that it does. It also wouldn't be advised. For everything that WDM does, we've done simpler and small, or that functionality is available in this plugin.

The confusion around `publicPath` isn't surprising - I could probably dig up four dozen issues asking about it from various projects relatively quickly. WDM and WDS (webpack-dev-server) have been abusing that setting for a long time, and it's caused kind of a state where no one understands how it's supposed to work, much less how to configure it correctly.

> Right now, if I set output.publicPath, my build directory must match this, and I must also set the static option as well.

That's the intention. If `context` differs from `output`, and the intent is to serve from output, then `static` should be set. But there are common scenarios in which that's not necessary. For example, [this simple config](https://github.com/shellscape/webpack-plugin-serve/blob/master/test/fixtures/simple/webpack.config.js) from our test fixtures.

**Comment by davidroeca** [comment]
Thanks for the clarification, and good to keep in mind re: WDM--makes sense.

So going forward with using this plugin for non-standard paths, I'll just aim to keep `output.path` and `output.publicPath` consistent, and will figure out a good scheme for handling the `static` config.

**Comment by shellscape** [comment]
@davidroeca sounds like a plan. Please do keep us posted on any shortcomings, quirks, gotchas, you encounter with the config.
