### ISSUE TITLE
liveReload: page not reloading 

### ISSUE THREAD

**Issue by jimfrenette** [shellscape/webpack-plugin-serve#62]
- Webpack Version: 4.17.1
- Operating System (or Browser): Fedora 29, Chrome 71
- Node Version: 10.13.0
- webpack-plugin-serve Version: 0.2.2

### How Do We Reproduce?

I can't seem to get the browser to reload after a build. here's the branch and dir of the app. all I'm doing to test this is an alert change in index.js,

https://github.com/jimfrenette/uiCookbook/tree/wp-plugin-serve/sidebars

### Expected Behavior

Reload the page when a build finishes

### Actual Behavior

Note this is my first attempt at using this plugin instead of `webpack-dev-server`. No errors are being output and the app does build, just not getting a page reload as expected.
Works as expected in master branch using the old webpack-dev-server:

https://github.com/jimfrenette/uiCookbook/tree/master/sidebars

**Comment by shellscape** [comment]
Thanks for posting this, it'll probably be a great reference for other folks, and it's given us another item to add to our FAQ. I'd wager any confusion on this one stems from use of webpack-merge, which can be tricky when working with split-configs, rather than wholesale merging two.

The problem with this particular setup is two fold:

1. The `webpack-plugin-serve/client` entry wasn't added to the dev config, nor the base config.
1. The `entry` from the base config (which is being merged into the dev config via webpack-merge) needs to be modified in order to merge with a value adding the WPS client

In `dev.config.js` add an entry of:

```js
  entry: {
    app: ['webpack-plugin-serve/client']
  },
```

In `base.config.js` change the entry to:

```js
  entry: {
    app: ['./js/index.js']
  },
```

Notet the `Array` values for `app` in both. That'll allow webpack-merge to merge those values, which is what we want. The resulting entry in `dev.config.js` will look like: `['./js/index.js', 'webpack-plugin-serve/client']`.

And some extra bonus observations:

- you can remove `--progress --colors` from your `dev` script in package.json, those are on/true by default.
- same goes for the `build` script, and `--hide-modules` isn't supported by webpack-nano. The functionality provided by `--hide-modules` in your previous webpack CLI should be put into the config in the `stats` property for the same effect.

**Comment by jimfrenette** [comment]
You're very welcome and thank you for the comprehensive response on the weekend no less! This worked great once I fixed my config issues per your detailed instructions. For reference, here is the commit, https://github.com/jimfrenette/uiCookbook/commit/20def8a99af9337cd79cb53a2378b1446c380cda

Additionally, I would be happy to contribute a recipe PR for using webpack-merge

**Comment by shellscape** [comment]
We'd love to have a recipe for that! Please do submit a PR!
