### ISSUE TITLE
documentation showing multiple named entry points in webpack.config.js

### ISSUE THREAD

**Issue by mindpivot** [shellscape/webpack-plugin-serve#66]
Documentation Is:

- [X] Missing
- [X] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The documentation currently shows how to set up webpack-plugin-serve using a single array in the "entry" configuration like so:

`entry: ['app.js', 'webpack-plugin-serve/client']`

It would be helpful to provide an example(s) of other, equally popular, entry configurations. For instance, if my webpack config currently looks like:

```js
entry: {
  main: ['src/index.js'],
  account: ['src/account/index.js'],
  legacyStyles: ['src/scss/styles.scss']
}
```

It is unclear how to properly "wire-up" `webpack-plugin-serve` based on the named and multiple entry point configurations

### Your Proposal for Changes

Provide further examples in that portion of the docs describing the entry point setup, and maybe explain why `webpack-plugin-serve/client` is needed and what it offers. That with the further example configurations may clear up any configuration questions moving forward

**Comment by PlayMa256** [comment]
Thank you for your issue!

Those client files were always a grey area for users, they didn't and actually don't know what those files do. 

This file is responsible for handling `HMR` and few other functionalities, specially all the overlays available. Without this file, when a change happen somewhere on your dependency tree, the browser won't be able to know about that change, hence won't update its content. 

Since it is basically another "dynamic" chunk, it has to contains, what we can call a "control" chunk (wps client file).

I did few tests on how we could simplify the import of it, on a common chunk imported on the page, but it failed miserably, specially due to how webpack handles hmr specifically per entrypoint.

I'll add an introductory section to the doc/faq to clarify why it has to contain this file and how to handle possible scenarios.

**Comment by PlayMa256** [comment]
@mindpivot pr merged, you can find descriptions on our FAQ and a recipe on our recipes folder!

Thank you for the issue!

**Comment by subatomicglue** [comment]
Maybe I'm not seeing where you wrote this example, but why bury it?  Why not list it directly after the array version `entry: ['app.js', 'webpack-plugin-serve/client']` you put on the front page?

Your documentation says:
`entry: ['app.js', 'webpack-plugin-serve/client']`

But my entry looks like:
```
entry: {
        'bundle': "./src/app.js",
       //  hmmmm, does it go here??   somehow?
    }
```

I have no idea how to patch your server in...!

Your FAQ says:
https://github.com/shellscape/webpack-plugin-serve/blob/HEAD/.github/FAQ.md#why-do-i-have-to-include-webpack-plugin-serveclient-in-the-entry

Which is quite long, but as far as I can tell doesn't address the above topic of how to patch in `webpack-plugin-serve/client` to the `entry`...

is the answer that it can't be?

**Comment by shellscape** [comment]
@subatomicglue I'm sorry you're confused by our documentation, but this may not be the right dev server for you. Adding entries to a webpack config is a fundamental skill required to work with webpack. We feature one, very common method for configuring an entry in our README. If users choose another method, it's expected that they understand the method that they've chosen and will at least consult the [webpack documentation](https://webpack.js.org/concepts/entry-points/) before opening or replying to a related issue. To conflate this as a lack of documentation on our end is unfair and misleading. I'd like to recommend going back over the webpack documentation on `entry`, which will clearly show how to add multiple entries to different options for that config property.
